POST http://127.0.0.1:8000/api/customers
Content-Type: application/json
Accept: application/json

{
    "type": "enterprise",
    "name": "Tech Company SARL",
    "email": "contact@techco.com",
    "phone": "+243900000000",
    "address": "Avenue Lumumba 45",
    "country": "DRC",
    "city": "Kinshasa",
    "nif": "NIF123456",
    "rccm": "RCCM987654",
    "idnat": "IDNAT456789"
}
